### ISSUE TITLE
Unexpected const in strict mode

### ISSUE THREAD

**Issue by zpwebbear** [vikkio88/vue-flag-icon#1]
When I used this plugin in Vue.js site development, and build project with webpack there is error on iOS devises   Unexpected const in strict mode
In vue-flag-icon/index.js line:4

`import './vendors'
import { Flag } from './components'

const VuePlugin = {
    install: function (Vue) {
        if (VuePlugin.installed) {
            return;
        }
        VuePlugin.installed = true;
        Vue.component('flag', Flag);
    }
};

if (typeof window !== 'undefined' && window.Vue) {
    window.Vue.use(VuePlugin);
}

export default VuePlugin;`

Changing 'const' to 'var' can solve this problem

I'm sorry for my English

**Comment by vikkio88** [comment]
hello there, that is mostly due to your version of node, what is it?

**Comment by zpwebbear** [comment]
Node 6.x

24 лип. 2017 20:48 "vikkio88" <notifications@github.com> пише:

**Comment by vikkio88** [comment]
that is really weird, ```const``` is supported from node 4, you sure you got 6.x?
I mean I could make pre-compile it with babel, but const is a standard introduced in ES2015, more than 2 years ago.
I suspect that you have node 0.12 legacy installed, make sure you have at least 4.x please

**Comment by zpwebbear** [comment]
Ok.Tomorrow I will come to the workplace and send you node -v output

24 лип. 2017 20:56 "vikkio88" <notifications@github.com> пише:

**Comment by vikkio88** [comment]
sure thing, thanks a lot for reporting though

**Comment by zpwebbear** [comment]
Hello, here is an output of node -v command
https://www.screencast.com/t/1OdOtH8hM

Bug appears only on when I run my web app on iOS devices.

2017-07-24 21:04 GMT+03:00 vikkio88 <notifications@github.com>:

**Comment by vikkio88** [comment]
That's so weird, I will transpile it, thanks again

**Comment by vikkio88** [comment]
if you use the webpack starter generated by vue-cli you will not have problems with this.

**Comment by fabiosussetto** [comment]
for everyone experiencing this issue, just update your webpack config to transpile this module too:

webpack.base.conf.js 

```
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), /vue-flag-icon/]
}
```

For me it still happens when I use webpack code splitting.

A transpiled version should be added to the npm package so that we can use this in the browser without having to manually transpile it, thanks.

**Comment by vikkio88** [comment]
If you want to do a pr about it,  I will merge it

**Comment by ChoOo7** [comment]
I can reproduce the issue
I have edited my webpack config too : 

//existing
      {
        test: /\.js$/,
        use: ['babel-loader?presets[]=es2015'],
        exclude: /node_modules/
      },

//-> added
      {
        test: /\.js$/,
        use: ['babel-loader?presets[]=es2015'],
        include: [/vue-flag-icon/]
      },
