### ISSUE TITLE
Jest support

### ISSUE THREAD

**Issue by VladZen** [vikkio88/vue-flag-icon#10]
Hi there! There are some difficulties with Jest testing. Due to the fact, that there is no compiled file i got some errors with ES6 modules while testing. I know there are some workaround in babelrc configs, but it would be great to have a dist file with compiled version. Thank you for your work!

**Comment by VladZen** [comment]
Solved by upgrading to Babel 7 and changing Jest configs

**Comment by vikkio88** [comment]
@vladzen, could you please write down what the config is, so people with the same issue can reference to your config? Thanks
