### ISSUE TITLE
Can someone explain how to include it in the nuxt config?

### ISSUE THREAD

**Issue by sowinski** [vikkio88/vue-flag-icon#11]
Hi,

can someone give an example how to include it with nuxt?

Thx

**Comment by vikkio88** [comment]
Hello, the instructions to install it are in the readme

**Comment by sowinski** [comment]
Where do I place this code in a nuxt project?

> Just declare the global Compoment with the use directive in your app
> 
> import FlagIcon from 'vue-flag-icon'
> Vue.use(FlagIcon);

Do I need to create a plugin for this?

**Comment by vikkio88** [comment]
If you want to open a PR feel free. I don't use nuxt so I wouldn't know

**Comment by alex-eri** [comment]
@sowinski 

SSR not working this way. Need to write module.

Without SSR it works:

```
  plugins: [
    { src: '~/plugins/flags.js', ssr: false }
  ],
```
~/plugins/flags.js
```
import Vue from 'vue'
import FlagIcon from 'vue-flag-icon'
Vue.use(FlagIcon)

```
