### ISSUE TITLE
Having Conflict Warning 

### ISSUE THREAD

**Issue by sanjeesk** [vikkio88/vue-flag-icon#14]
<img width="1437" alt="Screenshot 2020-06-12 at 11 30 06 AM" src="https://user-images.githubusercontent.com/44053292/84461931-41fbfe80-aca0-11ea-9da8-939bfa68ad55.png">

"Conflict: Multiple assets emit different content to the same filename img/ad.svg"

hi, i'm having warning in my project after install npm i --save vue-flag-icon via quasar vue : Kindly assist me how to resolve it thanks

**Comment by vikkio88** [comment]
Hello, I never used quasar, don't even know what it is, so I wouldn't know how to help you.

**Comment by vikkio88** [comment]
If you had searched between the issues you would have found this https://github.com/vikkio88/vue-flag-icon/issues/12
