### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by mtalhabalci** [vikkio88/vue-flag-icon#15]
Hello
Firstly i thank you for the library, its easy and very useful.
My issue is that i use just 3 flags in my project but all flags are installed in the node modules.
As i publish the project my bundle size increases about 5 mb.
Can i just select certain flags that im about to use.
Thanks.

**Comment by vikkio88** [comment]
unfortunately I wouldnt know how to help you with that, maybe you can avoid using this lib and go straight with icons if you are just using a few.
Bundle size is up to the bundler not a problem of this silly lib.

This [dude](https://github.com/vikkio88/vue-flag-icon/issues/9#issuecomment-429922007) solved it by bypassing the lib and using just a few lines of snippet, proving how useless this wrapper is lol.

sorry for the late reply
