### ISSUE TITLE
Seems not to work with nuxt

### ISSUE THREAD

**Issue by tim-kilian** [vikkio88/vue-flag-icon#16]
I am not able to use this with nuxt. My error message is a Syntax Error.

`
SyntaxError
Unexpected string
`

```
webpack:/external "vue-flag-icon":1:
Object.vue-flag-icon
```

`Missing stack frames`

**Comment by vikkio88** [comment]
I do not support nuxt, this project is a silly lib, check out the other issues, someone else solved it

**Comment by vikkio88** [comment]
the issue where someone suggested a solution is #11
