### ISSUE TITLE
Wrong import

### ISSUE THREAD

**Issue by noschang** [vikkio88/vue-flag-icon#17]
I'm trying to use your plugin with Nuxt.
When I run the application I get an error in this [file](https://github.com/vikkio88/vue-flag-icon/blob/20e06f293f83ef62292d2751e24dd123c846f64d/components/index.js#L1)

The fix is very simple, just change from 

 ```javascript
import Flag from './icon/Flag'
```

To

```javascript
import Flag from './icon/Flag.vue'
```
Can you do it please?

**Comment by vikkio88** [comment]
open up a PR will look into it
