### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by Pinnokkio** [vikkio88/vue-flag-icon#18]
-

**Comment by vikkio88** [comment]
look up those alternative solutions https://github.com/vikkio88/vue-flag-icon/issues/9

**Comment by Pinnokkio** [comment]
> look up those alternative solutions #9

Already tried that, don't work. Still not visible.

**Comment by vikkio88** [comment]
did you try installing the css lib separately and importing it in your main? have you got a css loader? what are you using as base app?

**Comment by vikkio88** [comment]
not enough info, closing this down
