### ISSUE TITLE
support squared icons

### ISSUE THREAD

**Issue by vikkio88** [vikkio88/vue-flag-icon#2]
as required by a user it would be nice to support the squared icon as well.
He provided as well a small hack to make it happen with a bool prop
```vue
<style>
</style>
<template>
    <span v-if="iso" class="flag-icon" :class="flagIconClass" :title="iso"></span>
</template>
<script>
    export default {
        name: 'flag',
        props: {
            iso: { type: String, default: null },
            squared: { type: Boolean, default: true },
        },
        computed: {
            flagIconClass() {
                return ((!!this.squared) ? 'flag-icon-squared ' : '') + 'flag-icon-' + this.iso.toLowerCase();
            }
        }
    }
</script>

```

**Comment by tornett** [comment]
Thank you. With this change it's possible to use `<flag iso="gb" :squared="false" />` which omits the flag-icon-squared CSS class resulting in the desirable rectangular flag rendering.

**Comment by vikkio88** [comment]
I was thinking more to make something like this
```html
<flag iso="gb" shape="circle" />
```
or
```html
<flag iso="gb" shape="square" />
```
and default to circle if not specified.
Boolean params are a symptom of bad design

**Comment by vikkio88** [comment]
oh lol just realised that is just squared or normal, so the bool will be fine
