### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by pratikpatel-aurochs** [vikkio88/vue-flag-icon#20]
Vue 3 support is available?

**Comment by vikkio88** [comment]
hey there, I haven't really worked with vue3 so I wouldn't known what to do. I accept PRs if you know what to change and how to make it compatible

**Comment by orafal-dev** [comment]
Tried with #22  please test. Didn't have time for testing properly.

**Comment by vikkio88** [comment]
sorry this repo is not maintained
