### ISSUE TITLE
Unable to set the title dynamically

### ISSUE THREAD

**Issue by joakimglaving** [vikkio88/vue-flag-icon#3]
I'm using the flags in a language switcher dropdown, which looks like this:

```
<b-nav-item-dropdown right-alignment>
            <span id="langTitle" slot="text"><flag :iso="currentLang" :title="langTitle" /></span>
            <b-dropdown-item v-on:click="changeLang('en', 'English')"><flag iso="gb" title="English" /> English</b-dropdown-item>
            <b-dropdown-item v-on:click="changeLang('fr', 'Français' )"><flag iso="fr" title="Français" /> Français</b-dropdown-item>
</b-nav-item-dropdown>
```

Whichever language is chosen, the correct flag shows at the top. The title also shows the correct language on initial load. However, when choosing a language in the dropdown, the flag correctly updates, but the title does not, it reverts back to the default title, e.g. 'gb' or 'fr'.

Inspecting the page in Chrome, this is what I found:

On initial load:
```
<span id="langTitle">
          <span title="English" class="flag-icon flag-icon-squared flag-icon-gb"></span>
</span>
```

After choosing another language in the dropdown:
```
<span id="langTitle" title="Français">
          <span title="fr" class="flag-icon flag-icon-squared flag-icon-fr"></span>
</span>
```

On initial load, the title seems to be added to the inner span (which is automatically created), but not when changing the language through the dropdown.

**Comment by vikkio88** [comment]
can I see the ```changeLang``` function, or the website where you are using it, so I can have a better idea.
It should be working fine.

**Comment by joakimglaving** [comment]
Here it is. It's only in development so there is no website that I can show you yet unfortunately.
```
changeLang(lang, newTitle){
      this.$i18n.locale = lang;
      var routeName = this.$route.name
      this.$store.commit('SET_LANG', lang)
      this.currentLang = lang

      //Have to do this because the flag is based on country, not language.
      if(this.currentLang == 'en'){
        this.currentLang = 'gb'
      }
      this.langTitle = newTitle
      this.$cookies.set("user_locale", this.currentLang)

      this.$router.push({ name: routeName, params: { locale: lang }})
    }
```

**Comment by vikkio88** [comment]
I will check it out later today, thanks for reporting it though

**Comment by vikkio88** [comment]
fixed in vue-flag-icon@1.0.5

**Comment by joakimglaving** [comment]
I updated to 1.0.5, but now I'm getting a lot of errors, 

`[Vue warn]: The computed property "title" is already defined as a prop.`
`[Vue warn]: Error in render function: "RangeError: Maximum call stack size exceeded"`
`RangeError: Maximum call stack size exceeded`

**Comment by vikkio88** [comment]
try  now with 1.0.6, tested locally and it is working

**Comment by joakimglaving** [comment]
Great! 1.0.6 is working perfectly :)

Thank you for the quick updates!
