### ISSUE TITLE
Can't resolve './icon/Flag'

### ISSUE THREAD

**Issue by Casara** [vikkio88/vue-flag-icon#4]
`ERROR in ./node_modules/vue-flag-icon/components/index.js
Module not found: Error: Can't resolve './icon/Flag' in '/home/ubuntu/workspace/FE/node_modules/vue-flag-icon/components'
 @ ./node_modules/vue-flag-icon/components/index.js 1:0-30
 @ ./node_modules/vue-flag-icon/index.js
 @ ./src/main.js`

**Comment by vikkio88** [comment]
that is not enough information, could you please tell me where you are using it?

**Comment by Casara** [comment]
This is the content of the webpack.config.js file:

```javascript
const path = require('path')
const webpack = require('webpack')
const CompressionPlugin = require('compression-webpack-plugin')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: 'dist/',
    filename: 'build.js'
  },
  module: {
    rules: [
      {
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [path.resolve('src')],
        options: {
          formatter: require('eslint-friendly-formatter')
        }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            i18n: '@kazupon/vue-i18n-loader',
            // Since sass-loader (weirdly) has SCSS as its default parse mode, we map
            // the "scss" and "sass" values for the lang attribute to the right configs here.
            // other preprocessors should work out of the box, no loader config like this necessary.
            'scss': 'vue-style-loader!css-loader!sass-loader',
            'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
          },
          include: [
            path.resolve(__dirname, './src'),
            path.resolve(__dirname, './node_modules/vuetify')
          ]
          // other vue-loader options go here
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          path.resolve(__dirname, './src'),
          path.resolve(__dirname, './node_modules/vuetify')
        ]
      },
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      },
      {
        test: /\.styl$/,
        loader: ['style-loader', 'css-loader', 'stylus-loader']
      }
    ]
  },
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    }
  },
  devServer: {
    historyApiFallback: true,
    noInfo: true
  },
  performance: {
    hints: false
  },
  plugins: [
    new CompressionPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: /\.(css|js|html)$/,
      threshold: 10240,
      minRatio: 0.8
    })
  ],
  devtool: '#eval-source-map'
}

if (process.env.NODE_ENV === 'production') {
  module.exports.devtool = '#source-map'
  // http://vue-loader.vuejs.org/en/workflow/production.html
  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ])
}
```

And in the src/main.js file:

```javascript
import Vue from 'vue'
import Vuetify from 'vuetify'
import FlagIcon from 'vue-flag-icon'

Vue.use(Vuetify)
Vue.use(FlagIcon)

new Vue({ // eslint-disable-line no-new
  el: '#app',
  render: h => h(App)
})
```

**Comment by vikkio88** [comment]
that is better, I will take a look once I have some time, in the meantime you can try with the fix someone suggested on #1

**Comment by Casara** [comment]
I solved by adding the following line:

```javascript
  resolve: {
    extensions: ['*', '.js', '.vue', '.json'],    // <-- line added 
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    }
  },
```
See more in vue-loader [#685](https://github.com/vuejs/vue-loader/issues/685).

**Comment by vikkio88** [comment]
aaah you weren't using the .vue file extensions?
I will add some docs to specify that

**Comment by Casara** [comment]
In my imports I put the extension, e.g.:

```javascript
import App from './App.vue'
```

**Comment by tiagoporto** [comment]
The same error 
```
Failed to compile.

./node_modules/vue-flag-icon/components/icon/Flag.vue
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <style>
| 
| </style>
 @ ./node_modules/vue-flag-icon/components/index.js 1:0-30
 @ ./node_modules/vue-flag-icon/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js
```

my webpack

```
const path = require('path')
const config = require('./.swillrc.json')
const webpack = require('webpack')
const paths = config.basePaths

const webpackConfig = {
  devServer: {
    open: true,
    overlay: true,
    watchContentBase: true,
    hot: true,
    host: 'localhost',
    port: '8080',
    contentBase: [
      path.join(__dirname, paths.src),
      path.join(__dirname, paths.src, 'logos')
    ]
  },
  entry: path.join(__dirname, paths.src, 'index.js'),
  output: {
    path: path.resolve(__dirname, process.env.NODE_ENV === 'production' ? paths.dist : paths.src),
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules)/,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true
          }
        }
      }, {
        test: /\.vue$/,
        exclude: /(node_modules)/,
        use: {
          loader: 'vue-loader',
          options: {
            cacheDirectory: true
          }
        }
      }, {
        test: /\.styl$/,
        use: [
          'style-loader',
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              ident: 'postcss',
              plugins: (loader) => [
                require('autoprefixer')(config.autoprefixerBrowsers)
              ]
            }
          },
          'stylus-loader'
        ]
      }, {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader'
        ]
      }, {
        test: /\.(ttf|woff|woff2|eot|svg)$/,
        use: [
          {
            loader: 'file-loader'
          }
        ]
      }
    ]
  },
  resolve: {
    alias: {
      vue: 'vue/dist/vue.common.js'
    }
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV)
      }
    }),
    new webpack.HotModuleReplacementPlugin()
  ]
}

process.env.NODE_ENV === 'production' && webpackConfig.plugins.push(new webpack.optimize.UglifyJsPlugin())

module.exports = webpackConfig
```


Adding the line doesn't work
```
extensions: ['*', '.js', '.vue', '.json'],
```

**Comment by vikkio88** [comment]
hi @tiagoporto 
The loader conf (vue loader section) that you provided in here seems different than the one that the guy in the post below that solved it.
I have been using this component with the starting template for a Vue2 SPA, which has preconfigured the vue file loader, I guess this lib should be transpiled to avoid this issue.
Try taking inspiration from this https://github.com/vikkio88/ascoota-web/blob/master/build/webpack.base.conf.js

**Comment by faisal5170** [comment]
ERROR in ./src/assets/vendors/vendors.min.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: E:\Faisal\Capitalfund\Capitalfund\ClientApp\src\assets\vendors\vendors.min.css:15:41705: Can't resolve '../vendors/flag-icon/flags/4x3/es-ct.svg' in 'E:\Faisal\Capitalfund\Capitalfund\ClientApp\src\assets\vendors'

  13 |
  14 | /*Flag icons*/
> 15 | .flag-icon-background{background-size:contain;background-position:50%;background-repeat:no-repeat}.fla.........................................................................




    at Object.emitError (E:\Faisal\Capitalfund\Capitalfund\ClientApp\node_modules\webpack\lib\NormalModule.js:169:6)
    at E:\Faisal\Capitalfund\Capitalfund\ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\postcss-cli-resources.js:138:28
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

Any one can help?

Its return errors when I add css and script inside angular.json file

**Comment by vikkio88** [comment]
@faisal5170 are you using a vue component inside an angular project?

**Comment by lipecss** [comment]
> The same error
> 
> ```
> Failed to compile.
> 
> ./node_modules/vue-flag-icon/components/icon/Flag.vue
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type.
> | <style>
> | 
> | </style>
>  @ ./node_modules/vue-flag-icon/components/index.js 1:0-30
>  @ ./node_modules/vue-flag-icon/index.js
>  @ ./src/index.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js
> ```
> 
> my webpack
> 
> ```
> const path = require('path')
> const config = require('./.swillrc.json')
> const webpack = require('webpack')
> const paths = config.basePaths
> 
> const webpackConfig = {
>   devServer: {
>     open: true,
>     overlay: true,
>     watchContentBase: true,
>     hot: true,
>     host: 'localhost',
>     port: '8080',
>     contentBase: [
>       path.join(__dirname, paths.src),
>       path.join(__dirname, paths.src, 'logos')
>     ]
>   },
>   entry: path.join(__dirname, paths.src, 'index.js'),
>   output: {
>     path: path.resolve(__dirname, process.env.NODE_ENV === 'production' ? paths.dist : paths.src),
>     filename: 'bundle.js'
>   },
>   module: {
>     rules: [
>       {
>         test: /\.(js|jsx)$/,
>         exclude: /(node_modules)/,
>         use: {
>           loader: 'babel-loader',
>           options: {
>             cacheDirectory: true
>           }
>         }
>       }, {
>         test: /\.vue$/,
>         exclude: /(node_modules)/,
>         use: {
>           loader: 'vue-loader',
>           options: {
>             cacheDirectory: true
>           }
>         }
>       }, {
>         test: /\.styl$/,
>         use: [
>           'style-loader',
>           'css-loader',
>           {
>             loader: 'postcss-loader',
>             options: {
>               ident: 'postcss',
>               plugins: (loader) => [
>                 require('autoprefixer')(config.autoprefixerBrowsers)
>               ]
>             }
>           },
>           'stylus-loader'
>         ]
>       }, {
>         test: /\.css$/,
>         use: [
>           'style-loader',
>           'css-loader'
>         ]
>       }, {
>         test: /\.(ttf|woff|woff2|eot|svg)$/,
>         use: [
>           {
>             loader: 'file-loader'
>           }
>         ]
>       }
>     ]
>   },
>   resolve: {
>     alias: {
>       vue: 'vue/dist/vue.common.js'
>     }
>   },
>   plugins: [
>     new webpack.DefinePlugin({
>       'process.env': {
>         NODE_ENV: JSON.stringify(process.env.NODE_ENV)
>       }
>     }),
>     new webpack.HotModuleReplacementPlugin()
>   ]
> }
> 
> process.env.NODE_ENV === 'production' && webpackConfig.plugins.push(new webpack.optimize.UglifyJsPlugin())
> 
> module.exports = webpackConfig
> ```
> 
> Adding the line doesn't work
> 
> ```
> extensions: ['*', '.js', '.vue', '.json'],
> ```

Im still with the same problem

**Comment by vikkio88** [comment]
@lipecss I think it might be because you are using this on the vue loader config

```js
test: /\.vue$/,
```

which means that only runs the vue loader on .vue files. try to see how webpack is setup on a base vue project, there this lib used to work.
