### ISSUE TITLE
limit icon usage

### ISSUE THREAD

**Issue by appinteractive** [vikkio88/vue-flag-icon#5]
We are using NuxtJS and when building our Project the console states that webpack is packaging EVERY ICON in this package, regardless of its used or not. Is there a way to limit the imported flags or to make the treeshaking of webpack working in that context?

<img width="843" alt="grafik" src="https://user-images.githubusercontent.com/432828/35733650-8175588c-081e-11e8-9903-535b690db5a3.png">

**Comment by vikkio88** [comment]
not that I know of from this side. I think it should be a webpack configuration from your side to prevent that from happening, or if you have any suggestion on how to achieve this from this lib side I am happy to take a PR for that.

**Comment by appinteractive** [comment]
The other thing is that the icons seem to not be optimized in any way (some are insanely huge) but that’s the library that you are using. Thinking about forking it. 

If we find a way we will PR it, thanks.

**Comment by parweb** [comment]
any news on this ?

**Comment by vikkio88** [comment]
I dont know if @appinteractive had fixed this, I have not.
Do you have any suggestions on how to do it? @parweb PR are always welcome

**Comment by parweb** [comment]
In theory I would load icons when needed

**Comment by vikkio88** [comment]
do you know how to achieve it in a webpack config? :smiley: 
I think is all a loader configuration rather than a problem related to this lib.
I think I'm going to close this issue

**Comment by appinteractive** [comment]
I did not fix it, it could be done by the webpack import() function but I think this has to be done in this package. Currently all assets are loader, always! And the sizes are not optimized ether. 

I fixed it for me by importing just the svgs (after optimizing then with svgmin which saved me up to 60%) and referencing them in my component (vue.js)
