### ISSUE TITLE
Icons always squared

### ISSUE THREAD

**Issue by Axelfowlie** [vikkio88/vue-flag-icon#6]
Heyho, 
not sure what I'm doing wrong, but no matter what I do, the Icons are always squared

`<flag :iso="selectedLanguage" :squared="false" />`
Should be that easy right?

Thanks in advance

**Comment by vikkio88** [comment]
what version are you using?

**Comment by vikkio88** [comment]
I am asking because if you checke in [here](https://github.com/vikkio88/vue-flag-icon#additional-props)
you can read
```
Additional Props
From 1.0.4 you can now specify two different properties:

squared : it will render the flag as a square if true, otherwise the flag will be rectangular shaped (true by default).
```

**Comment by Axelfowlie** [comment]
I'm using Version 1.0.6.
There's the prop in the Flag.vue

```
props: {
        iso: { type: String, default: null },
        title: { type: String, default: null },
        squared: { type: Boolean, default: true },
    },
```
No idea why it's not working :/

**Comment by vikkio88** [comment]
I will try to reproduce it later and let you know, you are the first one to report it.
Which flag is it in particular?

**Comment by Axelfowlie** [comment]
Currently just testing with 'us' and 'de'.
Thanks for checking :)

**Comment by vikkio88** [comment]
@Axelfowlie it looks all fine in here
![image](https://user-images.githubusercontent.com/248805/44408776-f02d3600-a558-11e8-8209-c05e0af4aeea.png)
```vue
<p>
      <flag iso="it" />
      <flag iso="it" :squared="false"/>
    </p>
    <p>
      <flag iso="us" />
    <flag iso="us" :squared="false"/>
    </p>
    
    <p>
      <flag iso="de" />
      <flag iso="de" :squared="false"/>
    </p>
```

**Comment by vikkio88** [comment]
could you add a screenshot? could be that is a visual effect @Axelfowlie

**Comment by Axelfowlie** [comment]
mh, that's strange

![Image](https://user-images.githubusercontent.com/3542098/44410268-58354980-a564-11e8-93dd-d600d323f2c5.png)

As you can see, the first flag has the squared param set to false.
Code looks like this:

```html
    <div  class="center">
        <label>Select Audio Language: </label>
        <select class="custom-select custom-select-sm col-lg-3" v-model="selectedLanguage">
            <option v-for="worker in workerList" :value="worker.iso">{{worker.name}}</option>
        </select>
        <flag :iso="selectedLanguage" :squared="false" />
        <flag :iso="selectedLanguage"/>

    </div>
```

Tried with Edge, Firefox and Chrome. They all look squared to me ....
No matter where in my App I'm using the flags, they are always squared. Gotta check if any css class conflicts.

thanks for the help :)

**Comment by vikkio88** [comment]
I would imagine it to be a css problem somewhere, sorry to hear about that, if you have any findings please report it in here so in case someone else search for them can read your findings

**Comment by suhailkc** [comment]
I don't know is it helpful, however I'm sharing here how I fix this flag icon square issue in my angular project. 

I have renamed 1x1 folder (node_modules > flag-icon-css > flags > 1x1) to 1x11 then compiled the scss
Naturally, I got scss compilation error
Then  I renamed the 1x11 folder back to 1x1
Then compiled again the scss
The magic happened all the flag icons changed from square to 4x3 ration icon.

**Comment by vikkio88** [comment]
thanks a lot @suhailkc, I think this might be helpful to whoever will search for a solution to that problem.
