### ISSUE TITLE
implicitly has an 'any' type error typescript not supported.

### ISSUE THREAD

**Issue by Try-Parser** [vikkio88/vue-flag-icon#8]
Error message : Try `npm install @types/vue-flag-icon` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-flag-icon';`

**Comment by vikkio88** [comment]
typescript not supported is not a bug, is a feature :smile: @Try-Parser 
happy to see a PR if you want to propose anything. I am not  using Typescript on this small utility

**Comment by Try-Parser** [comment]
@vikkio88  sure i will.

**Comment by ctp-placebo** [comment]
Any chance this will be supported in an update? Is there an alternative npm package I can use? 
If not I am going to A)make the index.d.ts file and submit it B)abandon 

TypeScript is gaining in popularity, imo it makes sense to update vue-flag-icon accordingly, as the vue cli v3 now explicitly asks if you want to use typescript on project creation.

**Comment by vikkio88** [comment]
hello @ctp-placebo, I dont use typescript, but I am open to PRs if you want to contribute and make the newer version support typescript

**Comment by ctp-placebo** [comment]
I have made a request on "Definately Typed" https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36324 because I failed at doing it myself :)

**Comment by vikkio88** [comment]
I don't know what that implies, but thanks :D
And sorry about this

**Comment by Try-Parser** [comment]
if you guys are using vue js you can add the declaration to global.d.ts 

declare module 'vue-flag-icon';
