### ISSUE TITLE
Not working on webpack, need to build to a js module

### ISSUE THREAD

**Issue by adrijere** [vikkio88/vue-flag-icon#9]
Hi,

I did everything is written in the README and when I try to run my project with npm run dev, this message appears:

``` 
ERROR  Failed to compile with 1 errors                                                                                
This dependency was not found:
* flag-icon-css/css/flag-icon.css in ./node_modules/vue-flag-icon/vendors/index.js

To install it, you can run: npm install --save flag-icon-css/css/flag-icon.css
```

Do you know any ideas ?

Kind regards

**Comment by vikkio88** [comment]
havent worked with it in at least a couple of months, I will check and let you know

**Comment by adrijere** [comment]
Any news ?

**Comment by vikkio88** [comment]
just tested and it works fine on a newly created vue project, I wonder where you are using it.
just 
```
yarn add this package
```
go to index.js and do 
```
import Vue from 'vue'
import App from './components/App.vue'
import Flag from  'vue-flag-icon'

Vue.config.productionTip = false

Vue.use(Flag)
```

then where you need to use it
```
<template>
  <div id="app">
    <flag iso="it" />
  </div>
</template>
```

and is there 
![image](https://user-images.githubusercontent.com/248805/46677149-f1cebe00-cbd9-11e8-8fc5-1611d69f8ae6.png)

**Comment by adrijere** [comment]
I tried as you said and that still not working.

I'm using Webpack, maybe do I have to do something on my webpack config ?

**Comment by vikkio88** [comment]
How are you installing it? Seems like you are missing the edge dep, add
some code otherwise is impossible to help you.

**Comment by adrijere** [comment]
I did 

```
npm install flag-icon-css vue-flag-icon
```

In my webpack I have 
```
'use strict'

const path = require('path')
const utils = require('./utils')
const config = require('../config')
const vueLoaderConfig = require('./vue-loader.conf')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}



module.exports = {
  context: path.resolve(__dirname, '../'),
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    }
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
              'scss': 'vue-style-loader!css-loader!sass-loader',
              'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
          }
      }
      //  options: vueLoaderConfig
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          'postcss-loader'
        ]
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader'
          }
        ]
      },
      {
        test: /\.(js|ts)$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client'), /vue-flag-icon/]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  },
  node: {
    // prevent webpack from injecting useless setImmediate polyfill because Vue
    // source contains it (although only uses it if it's native).
    setImmediate: false,
    // prevent webpack from injecting mocks to Node native modules
    // that does not make sense for the client
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty'
  }
}
```

Something seems wrong for you ?

Thanks for your time !

**Comment by vikkio88** [comment]
the only thing I can tell you is that this package already specifies `flag-icon-css` as dep, so you dont need to install it again.

Only the webpack does not help, I would like to see where you are using and how you are invoking it.

are you using a vue2 boilerplate? or a project generated with create-vue-app?

**Comment by adrijere** [comment]
I used vue-cli to generate the project.

In my main.js I have :
```
import FlagIcon from 'vue-flag-icon'

import App from './App.vue'
import router from './router/index'
import store from './store'

Vue.use(FlagIcon);
```

And in my component, I have in my template : 
```
<flag :iso="record.fields['Country']" />
```

**Comment by vikkio88** [comment]
that is really weird, could you try to remove `flag-icon-css` as dep and leave the package do its job?

what error do you get?

do you have the code on github?

**Comment by adrijere** [comment]
I tried to ` npm uninstall flag-icon-css && npm uninstall vue-flag-icon ` and install it again ` npm install vue-flag-icon ` and I always have the same error : 

```
 ERROR  Failed to compile with 1 errors                                                                              
This dependency was not found:
* flag-icon-css/css/flag-icon.css in ./node_modules/vue-flag-icon/vendors/index.js

To install it, you can run: npm install --save flag-icon-css/css/flag-icon.css
```

You can find the current code on this repository github : https://github.com/adrijere/SpartanBet

**Comment by adrijere** [comment]
Any update from your side ?

**Comment by vikkio88** [comment]
hey @adrijere, sorry, I havent been able to look into it, I will try later today

**Comment by vikkio88** [comment]
just checked, @adrijere, you are not using the create-vue template, but a webpack boilerplate, unfortunately I have no time to check on this today, but I am sure that I could solve this building my template rather than let a loader do the job. I will reopen the issue.

**Comment by vikkio88** [comment]
@adrijere it does work with a workaround 
![image](https://user-images.githubusercontent.com/248805/46963696-3ce74600-d09e-11e8-8a5f-184145d08c1d.png)

![image](https://user-images.githubusercontent.com/248805/46963712-4670ae00-d09e-11e8-930d-b0ca8c85e3cd.png)
on your `App.vue`, but that is not a clean solution, the correct way could be 2:
1. Setup webpack in order to load the style from Vue files on from the `node_modules` too
2. Make this a compiled package.

**Comment by adrijere** [comment]
Despite `@import '~flag-icon-css/css/flag-icon.css';` in `App.vue` I still have the same error, so weird. 

EDIT : Ok, with your workaround, I don't need anymore vue-flag-icon, just need to do a class like `flag-icon-{{nameCountry}}`
